// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: eCommerce.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ECommerceService_CreateProduct_FullMethodName = "/pb.eCommerceService/CreateProduct"
	ECommerceService_UpdateProduct_FullMethodName = "/pb.eCommerceService/UpdateProduct"
)

// ECommerceServiceClient is the client API for ECommerceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ECommerceServiceClient interface {
	CreateProduct(ctx context.Context, in *CreateProductReq, opts ...grpc.CallOption) (*Response, error)
	UpdateProduct(ctx context.Context, in *UpdateProductReq, opts ...grpc.CallOption) (*Response, error)
}

type eCommerceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewECommerceServiceClient(cc grpc.ClientConnInterface) ECommerceServiceClient {
	return &eCommerceServiceClient{cc}
}

func (c *eCommerceServiceClient) CreateProduct(ctx context.Context, in *CreateProductReq, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, ECommerceService_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eCommerceServiceClient) UpdateProduct(ctx context.Context, in *UpdateProductReq, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, ECommerceService_UpdateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ECommerceServiceServer is the server API for ECommerceService service.
// All implementations should embed UnimplementedECommerceServiceServer
// for forward compatibility.
type ECommerceServiceServer interface {
	CreateProduct(context.Context, *CreateProductReq) (*Response, error)
	UpdateProduct(context.Context, *UpdateProductReq) (*Response, error)
}

// UnimplementedECommerceServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedECommerceServiceServer struct{}

func (UnimplementedECommerceServiceServer) CreateProduct(context.Context, *CreateProductReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedECommerceServiceServer) UpdateProduct(context.Context, *UpdateProductReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedECommerceServiceServer) testEmbeddedByValue() {}

// UnsafeECommerceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ECommerceServiceServer will
// result in compilation errors.
type UnsafeECommerceServiceServer interface {
	mustEmbedUnimplementedECommerceServiceServer()
}

func RegisterECommerceServiceServer(s grpc.ServiceRegistrar, srv ECommerceServiceServer) {
	// If the following call pancis, it indicates UnimplementedECommerceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ECommerceService_ServiceDesc, srv)
}

func _ECommerceService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ECommerceServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ECommerceService_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ECommerceServiceServer).CreateProduct(ctx, req.(*CreateProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ECommerceService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ECommerceServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ECommerceService_UpdateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ECommerceServiceServer).UpdateProduct(ctx, req.(*UpdateProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ECommerceService_ServiceDesc is the grpc.ServiceDesc for ECommerceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ECommerceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.eCommerceService",
	HandlerType: (*ECommerceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProduct",
			Handler:    _ECommerceService_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _ECommerceService_UpdateProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eCommerce.proto",
}
